# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MasterGeotecnologiasDockWidget
                                 A QGIS plugin
 Complemento de prueba para el Máster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-15
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Carmen Cabeza
        email                : u149666@usal.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Geotecnologias_modulo_dockwidget_base.ui'))


class MasterGeotecnologiasDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(MasterGeotecnologiasDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.btn_comprobar.clicked.connect(self.recogerRuta)

    def recogerRuta(self, event):
        self.txt_ruta.setText(str(self.selector.filePath()))

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
